# Generated by Django 2.0.2 on 2018-09-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_corrected_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Division')),
            ],
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team', to='core.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='division',
            field=models.IntegerField(choices=[(1, 'Serie A'), (2, 'Premier League'), (3, 'Bundesliga'), (4, 'Ligue 1'), (5, 'Primera Division')], null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='ft_result',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, 'X'), (3, '2')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team', to='core.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='ht_result',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, 'X'), (3, '2')]),
        ),
    ]
