# Generated by Django 2.0.2 on 2018-09-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team_division_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Division'),
        ),
    ]
