# Generated by Django 2.1.2 on 2018-10-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180923_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.IntegerField(choices=[(1, 'Serie A'), (2, 'Premier League'), (3, 'Bundesliga'), (4, 'Ligue 1'), (5, 'Primera Division')]),
        ),
    ]
