# Generated by Django 2.0.2 on 2018-09-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_match_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='odds_away',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='odds_draw',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='odds_home',
            field=models.FloatField(null=True),
        ),
    ]
