# Generated by Django 2.1.2 on 2019-03-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auto_20190303_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('ft_result', models.CharField(choices=[('H', 'H'), ('D', 'X'), ('A', 'A')], max_length=1)),
                ('odds_home', models.FloatField(null=True)),
                ('odds_draw', models.FloatField(null=True)),
                ('odds_away', models.FloatField(null=True)),
                ('budget', models.IntegerField(default=0, null=True)),
                ('betted_outcome', models.CharField(blank=True, choices=[('H', 'H'), ('D', 'X'), ('A', 'A')], max_length=1)),
                ('stake', models.IntegerField(default=0, null=True)),
                ('result', models.CharField(blank=True, choices=[('H', 'H'), ('D', 'X'), ('A', 'A')], max_length=1)),
                ('success', models.BooleanField()),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bet_away_team', to='core.Team')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bet_division', to='core.Division')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bet_home_team', to='core.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
