# Generated by Django 2.1.2 on 2018-10-28 18:58

from django.db import migrations, models

from datafetch.models import DataFetchSettings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def initial_settings(apps, schema_editor):
        settings = DataFetchSettings.objects.create(
            difference_x_range_min=-0.09,
            difference_x_range_max=0.09,
            odds_1_min=1.38,
            odds_1_max=1.47,
            date_offset=7
        )
        settings.save()

    operations = [
        migrations.CreateModel(
            name='DataFetchSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference_x_range_min', models.FloatField(default=0)),
                ('difference_x_range_max', models.FloatField(default=0)),
                ('odds_1_min', models.FloatField(default=0)),
                ('odds_1_max', models.FloatField(default=0)),
                ('date_offset', models.IntegerField(default=7)),
            ],
        ),
        migrations.RunPython(initial_settings),
    ]
