# Generated by Django 2.1.2 on 2019-02-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFetchSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference_x_range_min', models.FloatField(default=0)),
                ('difference_x_range_max', models.FloatField(default=0)),
                ('odds_1_min', models.FloatField(default=0)),
                ('odds_1_max', models.FloatField(default=0)),
                ('date_offset', models.IntegerField(default=7)),
                ('odds_1_min_second', models.FloatField(default=0)),
                ('odds_1_max_second', models.FloatField(default=0)),
            ],
        ),
    ]
