# Generated by Django 2.1.2 on 2018-12-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafetch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafetchsettings',
            name='odds_1_max_second',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='datafetchsettings',
            name='odds_1_min_second',
            field=models.FloatField(default=0),
        ),
    ]
