# Generated by Django 2.1.2 on 2019-03-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190309_2332'),
        ('datafetch', '0003_datafetchsettings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafetchsettings',
            name='leagues',
            field=models.ManyToManyField(blank=True, related_name='leagues', to='core.Division'),
        ),
    ]
