# Generated by Django 2.1.2 on 2019-12-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datafetch', '0005_auto_20190407_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafetchsettings',
            old_name='difference_x_range_max',
            new_name='max_difference_x_probability',
        ),
        migrations.RenameField(
            model_name='datafetchsettings',
            old_name='difference_x_range_min',
            new_name='odds_1_max_probability',
        ),
        migrations.RenameField(
            model_name='datafetchsettings',
            old_name='odds_1_max',
            new_name='odds_1_min_probability',
        ),
        migrations.RenameField(
            model_name='datafetchsettings',
            old_name='odds_1_min',
            new_name='odds_2_max_probability',
        ),
        migrations.RenameField(
            model_name='datafetchsettings',
            old_name='odds_2_max',
            new_name='odds_2_min_probability',
        ),
        migrations.RemoveField(
            model_name='datafetchsettings',
            name='odds_2_min',
        ),
    ]
